### ISSUE TITLE
Mentoring

### ISSUE THREAD

**Issue by orta** [dblock/code#3]
- How does a team decide that they're big enough to do it?
- What are good resources?
- Are there any useful techniques?

**Comment by dblock** [comment]
I gave a talk on mentoring at QCon 2014: http://code.dblock.org/2014/10/07/video-mentoring-engineers-and-humans.html and have a detailed [Mentoring 101 post](http://code.dblock.org/2013/06/12/mentoring-101.html).

**Comment by orta** [comment]
![MRW someone tries to look over what I'm doing on my phone.](http://i.imgur.com/ycPyyG1.gif)

always got an answer.
