### ISSUE TITLE
More mongoid plugins

### ISSUE THREAD

**Issue by nofxx** [dblock/code#31]
Hey @dblock ! Some plugins for ya:

https://github.com/nofxx/mongoid-geospatial

https://github.com/thetron/mongoid-enum

**Comment by dblock** [comment]
Will add. Feel free to beat me to it with a PR

**Comment by dblock** [comment]
Closed via https://github.com/dblock/code.dblock.org/commit/498e321b39493b0c6de1ecedf260ceafafe8676d.
