### ISSUE TITLE
Configuring Bot Server with Devise

### ISSUE THREAD

**Issue by CKolkey** [dblock/code#68]
I was curious if you've had any experience configuring the bot-server oauth strategy to play nicely with devise's oauth. I'm currently trying to configure it, but I'm encountering a CSRF auth failure which I suspect is due to a "double auth" issue - both devise and Ruby bot server are attempting to do an oauth. I could be mistaken, but this is my thinking.

My current strategy is to have a user install a bot on their slack workspace (this fails with a CSRF error), and after, log in via oauth/slack to view their dashboard (this works fine with a boilerplate devise configuration for oauth).

If you have any suggestions on how I could accomplish this, or perhaps alternative ways to solve the problem, I'd be happy for the help.

**Comment by dblock** [comment]
You should open this as an issue in the appropriate slack-ruby project.

I've never combined Devise with a bot, have always rolled out my own.
